import os
import io
import base64
import zipfile
import cv2
import numpy as np
from typing import List, Optional
import jwt  # Needs: pip install pyjwt
from fastapi import FastAPI, UploadFile, File, HTTPException, Query, Depends, status
from fastapi.responses import StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel
from ImageProcessor import ImageProcessor

app = FastAPI()

# 1. READ THE SHARED JWT SECRET (Set by Docker environment)
JWT_SECRET = os.getenv("JWT_SECRET", "super-secret-fallback-key")
JWT_ALGORITHM = "HS256"

security = HTTPBearer()

# Configuración CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # En producción, cambia "*" por tu dominio frontend real
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ImageItem(BaseModel):
    filename: str
    content: str

class ImageList(BaseModel):
    files: list[ImageItem]


class TaskItem(BaseModel):
    name: str
    sigma: Optional[int] = 7      # Used for BLUR
    width: Optional[int] = 64     # Used for RESIZE
    height: Optional[int] = 64    # Used for RESIZE

class ImageItem(BaseModel):
    filename: str
    content: str

class ProcessImagesRequest(BaseModel):
    files: List[ImageItem]
    tasks: List[TaskItem]


# --- SHARED TOKEN VALIDATION DEPENDENCY ---
def verify_jwt(credentials: HTTPAuthorizationCredentials = Depends(security)):
    """
    Validates tokens generated by the auth_service using the shared JWT_SECRET.
    Handles padding fixes and url-safe variations seamlessly.
    """
    token = credentials.credentials
    try:
        # 1. Recuperamos el string desde el entorno
        secret_str = JWT_SECRET
        
        # 2. Agregar relleno (=) automáticamente si hace falta para que la longitud sea múltiplo de 4
        rem = len(secret_str) % 4
        if rem > 0:
            secret_str += "=" * (4 - rem)
            
        # 3. Decodificar de forma segura usando urlsafe_b64decode (tolera variaciones de caracteres Base64)
        secret_bytes = base64.urlsafe_b64decode(secret_str)
        
        # 4. Validar el token
        payload = jwt.decode(token, secret_bytes, algorithms=[JWT_ALGORITHM])
        return payload  
        
    except jwt.ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token expired. Please log in again via Auth Service."
        )
    except jwt.InvalidTokenError as e:
        print(f"Internal Crypto Traceback Error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid signature. Token verification failed."
        )
    

def decode_image(file_bytes):
    """Converts uploaded bytes to an OpenCV image."""
    nparr = np.frombuffer(file_bytes, np.uint8)
    img = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
    if img is None:
        raise HTTPException(status_code=400, detail="Invalid image format")
    return img

def encode_image(img):
    """Converts OpenCV image back to bytes for the response."""
    _, buffer = cv2.imencode(".jpg", img)
    return io.BytesIO(buffer)


# --- ROUTING (All endpoints protected by shared token validation) ---

@app.post("/process-image/")
async def process_image(
    task: str = Query(..., description="Task: GRAYSCALE, EDGES, BLUR, SHARPEN, THRESHOLD"),
    file: UploadFile = File(...),
    token_data: dict = Depends(verify_jwt) 
):
    contents = await file.read()
    img = decode_image(contents)
    processed_img = ImageProcessor.process(img, task.upper())
    image_stream = encode_image(processed_img)
    return StreamingResponse(image_stream, media_type="image/png")


# 2. Update the endpoint
@app.post("/process-images")
async def post_process_images(
    request: ProcessImagesRequest,
    token_data: dict = Depends(verify_jwt) 
):
    zip_buffer = io.BytesIO()
            
    with zipfile.ZipFile(zip_buffer, "a", zipfile.ZIP_DEFLATED) as zip_file:
        for idx, file in enumerate(request.files):
            filename = file.filename
            content = base64.b64decode(file.content)

            try:
                if content:
                    img = decode_image(content) # Assuming decode_image is defined elsewhere in your file
                    
                    # --- NEW: Loop through all tasks and apply them sequentially ---
                    for task in request.tasks:
                        t_name = task.name.upper()
                        if t_name == "GRAYSCALE":
                            img = ImageProcessor.to_grayscale(img)
                        elif t_name == "EDGES":
                            img = ImageProcessor.detect_edges(img)
                        elif t_name == "BLUR":
                            img = ImageProcessor.apply_blur(img, task.sigma)
                        elif t_name == "SHARPEN":
                            img = ImageProcessor.sharpen(img)
                        elif t_name == "THRESHOLD":
                            img = ImageProcessor.threshold(img)
                        elif t_name == "RESIZE":
                            img = ImageProcessor.resize(img, task.width, task.height)
                    # ---------------------------------------------------------------

                    success, buffer = cv2.imencode('.png', img)
                    
                    if success:
                        zip_file.writestr(f"proc_{idx}_{filename}", buffer.tobytes())
                    else:
                        print(f"Error encoding image: {filename}")
                        
            except Exception as e:
                print(f"Error while trying to parse image {filename}: {e}")
                zip_file.writestr(f"error_{idx}_{filename}.txt", f"Failed: {str(e)}")
    
    zip_buffer.seek(0)
    return StreamingResponse(
        zip_buffer, 
        media_type="application/zip",
        headers={"Content-Disposition": 'attachment; filename="processed_images.zip"'}
    )


@app.post("/resize/")
async def resize_image(
    width: int, 
    height: int, 
    file: UploadFile = File(...),
    token_data: dict = Depends(verify_jwt) 
):
    contents = await file.read()
    img = decode_image(contents)
    resized = ImageProcessor.resize(img, width, height)
    return StreamingResponse(encode_image(resized), media_type="image/jpeg")