spring.application.name=user
server.port=3000

#spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
#spring.datasource.username=shawdog
#spring.datasource.password=shawdog
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Custom JWT property
#jwt.secret=${JWT_SECRET}
jwt.secret=ZqZkOfoBL4AyS1NUKodvk9FZtso8MkijHHbUfrjZlYj